Wrapper for autoai_libs.nsfa transformer added
IBM/lale pull request #1330
Opened 2023-07-25 14:53 UTC by Rafalll-Maciasz

## Changes:
 - schema and wrapper for new autoai_libs transformer NSFA

2023-07-25 15:02 UTC, shinnar requested changes
I left a review on the previous PR https://github.com/IBM/lale/pull/1329 (which was closed in favor of this one).  Please take a look at the comments there

2023-07-26 08:28 UTC, Rafalll-Maciasz commented
You are right, input/output for fit and transform schema are changed to the `number` type.

2023-07-26 16:45 UTC, shinnar requested changes
Thanks for the fixes.  There is a remaining problem, due to these schemas being hosted in lale instead of in the same repository as the class they are wrapping

2023-07-26 16:45 UTC, shinnar commented on lale/lib/autoai_libs/__init__.py
> +from .nsfa import NSFA as NSFA
In order to solve the import error that results from when the lale.autai_libs module is imported, but the version of autai_libs being used does not have NSFA (as is happening now), this import should be behind a version gate.
An example of getting the version and testing it is here:
https://github.com/IBM/lale/blob/09f4c84140fc45a2488f405130fcf29831fe19bc/lale/lib/autoai_libs/cat_imputer.py#L159

2023-08-30 14:57 UTC, shinnar commented
Hi @Rafalll-Maciasz .  any updates on this PR?  As noted in the last review, it needs one minor change (putting back the simple wrapper impl class you had before, sorry about that), and I would then be happy to merge it.

2023-08-31 09:23 UTC, Rafalll-Maciasz commented
Hi @shinnar, no problem, I have added the impl wrapper class back.

2023-08-31 09:52 UTC, merged